### PR TITLE
Update GCC prerequisites

### PR DESCRIPTION
**Pull request by wallento**
Update the GCC prequisites to the latest versions. libgmp was not
available for download anymore.

### CODE REVIEW

**Comment by rofl0r** [comment]
did you test if this actually works ?

**Comment by wallento** [comment]
Yes. Are you experiencing problems?

**Comment by rofl0r** [comment]
no, but i can easily imagine breakage when updating 3 components.

**Comment by wallento** [comment]
Generally yes. But in this case those are libraries that are usually installed on the host where the actual versions differ a lot. I think in musl-cross they are only used for builds where they are statically built-in, e.g., to allow distribution (that's why people seem not hit the issue of the defect gmp link a lot).

Alternatively, #57 may be merged, but I doubt there are any issues with updating to the newest version. I have tested it with the OpenRISC build.

**Comment by GregorR** [comment]
The reasons I haven't previously upgraded are:

(1) Different versions work on different architectures. The specified versions are known to work (or at least compile) on all, but every time I've attempted an upgrade, they broke somewhere.
(2) Some versions work when integrated into the GCC build tree, others are not. I personally hate building with these deps in-tree, but every time I consider removing that feature, somebody whinges about it. I haven't checked recently, but for a long time only the ancient versions worked in in-tree builds.
(3) As of the last time I checked (again, not recently), they were the versions documented to work in GCC itself.

I'll look at the problem again when I get an opportunity.

**Comment by wallento** [comment]
Okay, no hurry. You should perhaps apply #57 then in the meantime, so that the build is not broken anymore. It fixes the URL, because they have moved the currently referenced version to the archive folder.

Cheers,
Stefan

**Comment by rofl0r** [comment]
+1 for merging #57

**Comment by abustin** [comment]
GMP_VERSION=4.3.2 is no longer available for download so the build always fails.  If this fixes that then I +1 this.

**Pull request merged**
